CREATE TABLE categories(
    id int generated by default as identity (start with 1),
    name VARCHAR(30),
    PRIMARY KEY(id)
);

CREATE TABLE products(
    id int generated by default as identity (start with 1),
    name VARCHAR(40),
    description VARCHAR(120),
    stock INT NOT NULL,
    price INT NOT NULL,
    status VARCHAR(20),
    category_id INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT category_id
            FOREIGN KEY(category_id)
                REFERENCES categories(id)
);